https://kambale.dev/numpy-vs-jax

In [1]:
!pip install numpy
!pip install jax

In [2]:
!pip install jaxlib

In [3]:
import numpy as np

# create a 1D array
npArrOne = np.array([1, 2, 3])
print(npArrOne)

# create a 2D array
npArrTwo = np.array([[1, 2], [3, 4]])
print(npArrTwo)


[1 2 3]
[[1 2]
 [3 4]]


In [4]:
import jax.numpy as jnp

# create a 1D array
jxArrOne = jnp.array([1, 2, 3])
print(jxArrOne)

# create a 2D array
jxArrTwo = jnp.array([[1, 2], [3, 4]])
print(jxArrTwo)


[1 2 3]
[[1 2]
 [3 4]]


In [5]:
# indexing in numpy
npArr = np.array([1, 2, 3])
print(npArr[0])  
# output: 1

# indexing in jax
jxArr = jnp.array([1, 2, 3])
print(jxArr[0])  
# output: 1


1
1


I believe that index_update has been deprecated...
https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-2-march-16-2022

In [6]:
# update an element in numpy
npArr = np.array([1, 2, 3])
npArr[0] = 4
print(npArr)  
# output: [4, 2, 3]

# update an element in jax
jxArr = jnp.array([1, 2, 3])
jxArr = jnp.index_update(b, 0, 4)
print(jxArr)  
# output: [4, 2, 3]


[4 2 3]


AttributeError: module 'jax.numpy' has no attribute 'index_update'

https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html

In [8]:
# update an element in numpy
npArr = np.array([1, 2, 3])
npArr[0] = 4
print(npArr)  
# output: [4, 2, 3]

# update an element in jax
jxArr = jnp.array([1, 2, 3])
jxArr = jxArr.at[0].set(4)
print(jxArr)  
# output: [4, 2, 3]

[4 2 3]
[4 2 3]
