https://kambale.dev/numpy-vs-jax

In [1]:
!pip install numpy
!pip install jax

In [2]:
!pip install jaxlib

In [3]:
import numpy as np

# create a 1D array
npArrOne = np.array([1, 2, 3])
print(npArrOne)

# create a 2D array
npArrTwo = np.array([[1, 2], [3, 4]])
print(npArrTwo)


[1 2 3]
[[1 2]
 [3 4]]


In [4]:
import jax.numpy as jnp

# create a 1D array
jxArrOne = jnp.array([1, 2, 3])
print(jxArrOne)

# create a 2D array
jxArrTwo = jnp.array([[1, 2], [3, 4]])
print(jxArrTwo)


[1 2 3]
[[1 2]
 [3 4]]
