https://kambale.dev/numpy-vs-jax

In [1]:
!pip install numpy
!pip install jax

In [2]:
!pip install jaxlib

In [3]:
import numpy as np

# create a 1D array
npArrOne = np.array([1, 2, 3])
print(npArrOne)

# create a 2D array
npArrTwo = np.array([[1, 2], [3, 4]])
print(npArrTwo)


[1 2 3]
[[1 2]
 [3 4]]


In [4]:
import jax.numpy as jnp

# create a 1D array
jxArrOne = jnp.array([1, 2, 3])
print(jxArrOne)

# create a 2D array
jxArrTwo = jnp.array([[1, 2], [3, 4]])
print(jxArrTwo)


[1 2 3]
[[1 2]
 [3 4]]


In [5]:
# indexing in numpy
npArr = np.array([1, 2, 3])
print(npArr[0])  
# output: 1

# indexing in jax
jxArr = jnp.array([1, 2, 3])
print(jxArr[0])  
# output: 1


1
1


I believe that index_update has been deprecated...
https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-2-march-16-2022

In [6]:
# update an element in numpy
npArr = np.array([1, 2, 3])
npArr[0] = 4
print(npArr)  
# output: [4, 2, 3]

# update an element in jax
jxArr = jnp.array([1, 2, 3])
jxArr = jnp.index_update(b, 0, 4)
print(jxArr)  
# output: [4, 2, 3]


[4 2 3]


AttributeError: module 'jax.numpy' has no attribute 'index_update'

https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html

In [8]:
# update an element in numpy
npArr = np.array([1, 2, 3])
npArr[0] = 4
print(npArr)  
# output: [4, 2, 3]

# update an element in jax
jxArr = jnp.array([1, 2, 3])
jxArr = jxArr.at[0].set(4)
print(jxArr)  
# output: [4, 2, 3]

[4 2 3]
[4 2 3]


In [9]:
# broadcasting in numpy
npArrOne = np.array([[1, 2], [3, 4]])
npArrTwo = np.array([10, 20])
print(npArrOne + npArrTwo)  
# output: [[11, 22], [13, 24]]


[[11 22]
 [13 24]]


In [10]:
# broadcasting in jax
jxArrOne = jnp.array([[1, 2], [3, 4]])
jxArrTwo = jnp.array([10, 20])
print(jxArrOne + jxArrTwo) 
# output: [[11, 22], [13, 24]]


[[11 22]
 [13 24]]


vmap was moved from jnp to jax itself, requiring this import and syntax

In [14]:
# vmap in Jax
from jax import vmap
def add(x, y):
    return x + y

jxArrOne = jnp.array([[1, 2], [3, 4]])
jxArrTwo = jnp.array([[10, 20], [30, 40]])

# apply add to multiple inputs using broadcasting
jxArrThree = vmap(add)(jxArrOne, jxArrTwo)
print(jxArrThree)  
# output: [[11, 22], [33, 44]]


[[11 22]
 [33 44]]


In [15]:
# matrix multiplication in numpy
import numpy as np
import time

npArrOne = np.random.rand(1000, 1000)
npArrOne = np.random.rand(1000, 1000)

start = time.time()
npArrThree = np.dot(npArrOne, npArrOne)
end = time.time()

print("NumPy time:", end - start)


NumPy time: 0.04420304298400879


In [16]:
# matrix multiplication in jax
import jax.numpy as jnp
from jax import jit

jxArrOne = jnp.random.rand(1000, 1000)
jxArrTwo = jnp.random.rand(1000, 1000)

@jit
def matmul(jxArrOne, jxArrTwo):
    return jnp.dot(jxArrOne, jxArrTwo)

start = time.time()
jxArrThree = matmul(jxArrOne, jxArrOne)
end = time.time()

print("JAX time:", end - start)


AttributeError: module 'jax.numpy' has no attribute 'random'

Original code uses the np style of random number generation--this has changed.

In [18]:
import jax
from jax import jit

jxArrOne  = jax.random.uniform(jax.random.PRNGKey(0), (1000, 1000), dtype=jnp.float32) 
jxArrTwo  = jax.random.uniform(jax.random.PRNGKey(0), (1000, 1000), dtype=jnp.float32)

@jit
def matmul(jxArrOne, jxArrTwo):
    return jnp.dot(jxArrOne, jxArrTwo)

start = time.time()
jxArrThree = matmul(jxArrOne, jxArrOne)
end = time.time()

print("JAX time:", end - start)

JAX time: 0.023059606552124023
