https://www.tensorflow.org/tutorials/quickstart/beginner

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2024-05-11 05:05:58.997527: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-11 05:05:58.997663: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-11 05:05:59.197768: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


TensorFlow version: 2.15.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/opt/conda/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 1.1150963 , -0.23684093, -0.6857538 ,  0.18868078,  0.24155553,
         0.6750523 , -0.83505654,  0.30244145, -0.37657112,  0.71526015]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.22921562, 0.05930691, 0.03785689, 0.09076262, 0.09569082,
        0.1476167 , 0.03260646, 0.10169806, 0.05157286, 0.15367301]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

1.9131361

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8536 - loss: 0.4930
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9536 - loss: 0.1551
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9672 - loss: 0.1069
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9721 - loss: 0.0887
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9771 - loss: 0.0719


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9768 - loss: 0.0750


[0.0749845951795578, 0.9768000245094299]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.0450803e-08, 4.9627472e-11, 3.5223624e-05, 1.1088431e-04,
        1.3125450e-13, 7.0601466e-08, 1.7027682e-15, 9.9985325e-01,
        8.1598159e-09, 4.2716411e-07],
       [3.0320822e-07, 1.2442307e-03, 9.9875259e-01, 2.1805024e-06,
        1.6888503e-13, 6.2699876e-08, 1.2978899e-07, 4.6745025e-12,
        4.2526918e-07, 2.5318240e-13],
       [1.1793157e-07, 9.9957377e-01, 1.3168923e-05, 2.0422769e-06,
        1.9161216e-05, 6.8019249e-06, 5.7012086e-05, 2.1650897e-04,
        1.1098544e-04, 4.6649069e-07],
       [9.9997187e-01, 6.8058563e-09, 6.2917811e-06, 4.7952815e-09,
        6.8079892e-08, 1.1856728e-06, 1.7737257e-06, 9.6623917e-06,
        1.7512169e-11, 9.1124684e-06],
       [3.1771012e-06, 1.5317037e-08, 2.3532019e-05, 1.0444679e-07,
        9.9262369e-01, 4.0813168e-07, 2.0637889e-07, 1.8271930e-04,
        3.0302260e-08, 7.1660443e-03]], dtype=float32)>